version: "3.8"

services:

    app:
      container_name: rubi-ui-customer
      restart: unless-stopped
      build:
        context: .
        dockerfile: ./Dockerfile
      image: rubi/ui/customer/stg  
      
#       volumes:
#           - ./:/var/www/app
#       environment:
#           - APP_ENV=local
#       env_file:
#         - ./.env
      
      ports:
          - 8800:80

networks:
  default:
    external: true
    name: mac
