version: "3.7"
services:
  app:
    image: kooldev/node:16
    command: ["yarn", "dev"]
    ports:
      - "${KOOL_APP_PORT:-80}:5173"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
      VITE_BASE_URL: "https://api.dev.rubi-ai.com/api"
      # VITE_BASE_URL: "https://api.staging.rubi-ai.com/api"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
