version: "3.8"

services:

    app:
        build:
          context: ""
          dockerfile: ./Dockerfile
 #       volumes:
 #           - ./:/var/www/app
 #       environment:
 #           - APP_ENV=local
 #       env_file:
 #         - ./.env
        restart: unless-stopped
        ports:
            - 8800:80

networks:
  default:
    external: true
    name: mac
