<script setup lang="ts">
import { VDataTable } from 'vuetify/labs/VDataTable'

interface Props {
  showBtnRun?: boolean
}

interface Emit {
  (e: 'close', value: boolean): void
}

defineProps<Props>()

defineEmits<Emit>()

const colunsScore = ref([
  {
    checkTitle: 'Check Readability',
    circleTitle: 'Flesch-Kincaid<br>Reading Ease',
    color: 'primary',
    circleChecked: true,
    score: 82.9,
    scoreLabel: '',
    radio_value: 'readability',
    description: `Based on our <u>Readability Score Study</u> ~70% of the top results in Google had a Dale-Chall Readability Grade between (5.6 - 8.4) <br><br>

Test for measuring the readability using words familiar to a fourth grader. The lower the score the more readable.`,
  },
  {
    checkTitle: 'Check Readability',
    circleTitle: 'FORCAST Grade<br>Level',
    color: 'warning',
    circleChecked: false,
    score: null,
    scoreLabel: '',
    radio_value: '4234',
    description: `Based on our <u>Readability Score Study</u> ~70% of the top results in Google had a Dale-Chall Readability Grade between (5.6 - 8.4) <br><br>

Test for measuring the readability using words familiar to a fourth grader. The lower the score the more readable.`,
  },
  {
    checkTitle: 'Check Readability',
    circleTitle: 'Gunning-Fog<br>Index',
    color: 'primary-300',
    circleChecked: true,
    score: 7.5,
    scoreLabel: 'Grade',
    radio_value: '34234',
    description: `Based on our <u>Readability Score Study</u> ~70% of the top results in Google had a Dale-Chall Readability Grade between (5.6 - 8.4) <br><br>

Test for measuring the readability using words familiar to a fourth grader. The lower the score the more readable.`,
  },
  {
    checkTitle: 'Check Readability',
    circleTitle: 'Dale-Chall<br>Readability Grade',
    color: 'info',
    circleChecked: true,
    score: 7.5,
    scoreLabel: 'Grade',
    radio_value: '657567',
    description: `Based on our <u>Readability Score Study</u> ~70% of the top results in Google had a Dale-Chall Readability Grade between (5.6 - 8.4) <br><br>

Test for measuring the readability using words familiar to a fourth grader. The lower the score the more readable.`,
  },
])

const currentColum = ref(0)

const currentColumItem = computed(() => colunsScore.value[currentColum.value])

function setColum(index: number) {
  const nextIndex = currentColum.value + index

  if (nextIndex < 0)
    return
  if (nextIndex >= colunsScore.value.length)
    return

  currentColum.value = nextIndex
}

const data = ref([
  {
    matched: 'The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela',
    average_score: 81,
    websites: [
      {
        website: 'www.examplecitation.com',
        url: 'https://www.examplecitation.com/2004/12/05/today-is-the-day',
      },
      {
        website: 'www.examplecitation2.com',
        url: 'https://www.examplecitation.com/2004/12/05/today-is-the-day',
      },
    ],
  },
  {
    matched: 'The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela',
    average_score: 81,
    websites: [
      {
        website: 'www.examplecitation3.com',
        url: 'https://www.examplecitation.com/2004/12/05/today-is-the-day',
      },
      {
        website: 'www.examplecitation4.com',
        url: 'https://www.examplecitation.com/2004/12/05/today-is-the-day',
      },
    ],
  },
])

const headers = [
  { title: 'Matched Plagiarized Phrase', sortable: false, key: 'matched' },
  { title: 'Averag\nScore', key: 'average_score' },
  { title: 'Matched\nWebsites', key: 'websites' },
]

const radioSelected = ref()

const cardsHighlighting = computed(() => [
  {
    title: 'AI Detection Highlighting Color Key',
    show: radioSelected.value === 'ai',
    highlightings: [
      {
        name: '90% confidence this sentence was generated by AI.',
        color: '#EA5455',
      },
      {
        name: '70% confidence this sentence was generated by AI.',
        color: '#FF9F43',
      },
      {
        name: '50% confidence this sentence was generated by AI.',
        color: '#FBFF43',
      },
      {
        name: '70% confidence this sentence was human written.',
        color: '#28C76F',
      },
      {
        name: '90% confidence this sentence was human written.',
        color: '#48B5FF',
      },
    ],
  },
  {
    title: 'Readability Highlighting Color Key',
    show: radioSelected.value === 'readability',
    highlightings: [
      {
        name: 'Sentence is hard to read. (over 20 syllables)',
        color: '#EA5455',
      },
      {
        name: 'Sentence is very hard to read. (over 30 syllables)',
        color: '#FF9F43',
      },
      {
        name: 'This word is over 13 characters. Consider using a different, shorter word.',
        color: '#FBFF43',
      },
      {
        name: 'This word is over 4 syllables. Consider using a word with less syllables.',
        color: '#28C76F',
      },
      {
        name: 'This is an adverb. Try to use a more concise word.',
        color: '#48B5FF',
      },
    ],
  },
])

const cardsHighlightingShowing = computed(() => cardsHighlighting.value.find(item => item.show))
</script>

<template>
  <div class="bg-background-card mt-5 pb-15">
    <VRow
      class="content-m mx-2"
      justify="space-between"
      align-content="center"
      align="center"
    >
      <VCol>
        <h3 class="text-h3">
          SPI Scoring
        </h3>
        <p class="text-body-2-medium">
          Surveillance and Plagiarism Identifier
        </p>
      </VCol>
      <VSpacer />
      <DialogCloseBtn
        rounded="sm"
        class="mr-2"
        @click="$emit('close')"
      />
    </VRow>
    <VDivider
      v-if="!showBtnRun"
      class="mx-5"
    />

    <VRow
      justify="center"
      align="start"
      class="mt-5"
    >
      <VCol
        cols="12"
        lg="4"
        md="6"
        sm="6"
      >
        <VCardText class="d-flex flex-column justify-center align-center text-center ps-2 h-100">
          <VCheckbox
            label="SPI AI Detection"
            class="mt-5"
          />

          <VProgressCircular
            model-value="75"
            color="error"
            size="173"
            width="10"
            class="mt-5"
            style="position: relative;"
          >
            <VTooltip
              location="bottom"
              max-width="170"
              content-class="content-tooltip-shadow"
            >
              <template #activator="{ props }">
                <IconBtn
                  v-bind="props"
                  icon="tabler-info-circle"
                  color="primary"
                  style="position: absolute; top: 15px;"
                />
              </template>

              <span
                class="text-caption mt-5 text-text-color-body"
                style="text-align: start;"
              >
                SPI Originality Score. This score reflects our AI's confidence in predicting that the content scanned was produced by an AI tool. A score of 90% original and 10% AI should be thought of as "We are 90% confident that this content was created by a human" and NOT that 90% of the article is Human and 10% AI.

                Learn More
              </span>
            </VTooltip>
            <span class="text-body-1">AI Detection Score</span>
          </VProgressCircular>
          <span class="text-body-2-medium mt-5"><span class="text-error">75%</span> AI</span>
          <VRadioGroup
            v-model="radioSelected"
            column
          >
            <VRadio
              label="Highlight results"
              class="mt-5"
              color="primary"
              value="ai"
            />
          </VRadioGroup>
        </VCardText>
      </VCol>
      <VCol
        cols="12"
        lg="4"
        md="6"
        sm="6"
      >
        <VCardText class="d-flex flex-column justify-center align-center text-center ps-2 h-100">
          <VCheckbox
            label="Detect Plagiarism"
            class="mt-5"
          />

          <VProgressCircular
            model-value="100"
            color="success"
            size="173"
            width="10"
            class="mt-5"
            style="position: relative;"
          >
            <VTooltip
              location="bottom"
              max-width="170"
              content-class="content-tooltip-shadow"
            >
              <template #activator="{ props }">
                <IconBtn
                  v-bind="props"
                  icon="tabler-info-circle"
                  color="primary"
                  style="position: absolute; top: 15px;"
                />
              </template>

              <span
                class="text-caption mt-5 text-text-color-body"
                style="width: 170px; text-align: start;"
              >
                Based on our <u>Readability Score Study</u> ~70% of the top results in Google had a Dale-Chall Readability Grade between (5.6 - 8.4) <br><br>

                Test for measuring the readability using words familiar to a fourth grader. The lower the score the more readable.
              </span>
            </VTooltip>
            <div class="d-flex flex-column justify-center align-center">
              <span class="text-body-1 mt-5">Plagiarism Score</span>
              <VIcon
                icon="tabler-check"
                color="success"
                size="54"
                class="svg-strock-1"
              />
            </div>
          </VProgressCircular>
          <span class="text-body-2-medium mt-5"><span class="text-success">0%</span> Plagiarized</span>
          <VRadioGroup
            v-model="radioSelected"
            column
          >
            <VRadio
              v-model="radioSelected"
              label="Highlight results"
              class="mt-5"
              color="primary"
              value="plagiarism"
            />
          </VRadioGroup>
        </VCardText>
      </VCol>
      <VCol
        cols="12"
        lg="4"
        md="6"
        sm="6"
      >
        <VCardText class="d-flex flex-column justify-center align-center text-center ps-2 h-100">
          <VCheckbox
            label="Check Readability"
            class="mt-5"
          />

          <VProgressCircular
            model-value="100"
            :color="currentColumItem.color"
            size="173"
            width="10"
            class="mt-5"
            style="position: relative;"
          >
            <VTooltip
              location="bottom"
              max-width="170"
              content-class="content-tooltip-shadow"
            >
              <template #activator="{ props }">
                <IconBtn
                  v-bind="props"
                  icon="tabler-info-circle"
                  color="primary"
                  style="position: absolute; top: 15px;"
                />
              </template>

              <span
                class="text-caption mt-5 text-text-color-body"
                style="width: 170px; text-align: start;"
                v-html="currentColumItem.description"
              />
            </VTooltip>
            <div class="d-flex flex-column justify-center align-center">
              <span
                class="text-body-1 mt-5"
                v-html="currentColumItem.circleTitle"
              />
              <VIcon
                v-if="currentColumItem.circleChecked"
                icon="tabler-check"
                color="success"
                size="54"
                class="svg-strock-1"
              />
            </div>
          </VProgressCircular>
          <VRow
            align="center"
            class="mt-5"
          >
            <VIcon
              icon="tabler-chevron-left"
              class="mr-2 cursor-pointer"
              @click="setColum(-1)"
            />
            <span
              class="text-body-2-medium text-primary  font-weight-medium"
              style="width: 85px;"
            >{{ currentColumItem.scoreLabel }} {{ currentColumItem.score }}</span>
            <VIcon
              icon="tabler-chevron-right"
              class="ml-2 cursor-pointer"
              @click="setColum(1)"
            />
          </VRow>
          <VRadioGroup
            v-model="radioSelected"
            column
          >
            <VRadio
              label="Highlight results"
              class="mt-5"
              color="primary"
              :value="currentColumItem.radio_value"
            />
          </VRadioGroup>
        </VCardText>
      </VCol>
    </VRow>
    <VRow
      v-if="showBtnRun"
      justify="center"
      class="mt-1"
    >
      <VBtn> Run Audit </VBtn>
    </VRow>
    <VRow
      v-if="showBtnRun"
      justify="center"
      class="mt-10 mb-5"
    >
      <span class="text-caption text-muted">
        Each submission costs 1 credit
      </span>
    </VRow>
    <div
      v-if="showBtnRun"
      class="py-2 bg-background"
    />
    <VDivider
      v-else
      class="mx-5"
    />
    <VCard
      v-if="!cardsHighlighting.find(item => item.show)"
      elevation="0"
    >
      <VCardText>
        <p class="text-p-bold">
          Matched Phrases <span class="text-rubi-red">(2)</span>
        </p>
        <VDataTable
          :headers="headers"
          :items="data"
          show-expand
        >
          <template #item.average_score="{ item }">
            <VChip
              color="rubi-red"
              variant="flat"
              rounded="sm"
            >
              {{ item.raw.average_score }}%
            </VChip>
          </template>
          <template #item.websites="{ item }">
            {{ item.raw.websites.length }}
          </template>
          <template #expanded-row="{ columns, item }">
            <tr class="p-2">
              <td :colspan="columns.length">
                <VRow
                  v-for="website in item.raw.websites"
                  :key="website.website"
                  class="my-2"
                >
                  <VCol cols="10">
                    <p class="p-small-bold">
                      {{ website.website }}
                    </p>
                    <a
                      :href="website.url"
                      target="_blank"
                      rel="noopener noreferrer"
                    >{{ website.url }}</a>
                  </VCol>
                  <VCol cols="1">
                    <VBtn
                      :href="website.url"
                      target="_blank"
                      rel="noopener noreferrer"
                      variant="plain"
                      color="secundary"
                      icon="tabler-external-link"
                    />
                  </VCol>
                </VRow>
              </td>
            </tr>
          </template>
        </VDataTable>
      </VCardText>
    </VCard>
    <VCard
      v-else
      elevation="0"
      :title="cardsHighlightingShowing?.title"
    >
      <div class="my-1" />
      <VCardText
        v-for="highlight in cardsHighlightingShowing?.highlightings"
        :key="highlight.name"
        align="center"
        class="mb-5 ml-5"
      >
        <VRow>
          <VAvatar
            size="26"
            :style="`background-color: ${highlight.color};`"
          /> <span class="ml-5 text-h6">{{ highlight.name }}</span>
        </VRow>
      </VCardText>
    </VCard>
  </div>
</template>
